---
# Comment here
# file: docker.yml

- name: Docker Configuration
  hosts: site
  become: yes

  tasks: 

    - 
      name: Docker Roles
      block:
        - name: Apply Docker Role
          ansible.builtin.import_role:
            name: docker