---
# Apply devsec hardening roles for ssh and os.
# file: hardening.yml

- name: DevSec Configuration
  hosts: site
  become: true

  tasks:
    -
      name: Check if ansible.devsec file exists
      ansible.builtin.stat:
        path: "~/ansible.devsec"
      register: file_result
    -
      name: DevSec Roles
      when: not file_result.stat.exists

      vars:
        sysctl_overwrite:
          net.ipv4.ip_forward: 1
        network_ipv6_enable: false

      block:

        - name: Apply DevSec SSH Hardening Role
          ansible.builtin.import_role:
            name: devsec.hardening.ssh_hardening

        - name: Apply DevSec OS Hardening role
          ansible.builtin.import_role:
            name: devsec.hardening.os_hardening

        - name: Touch ansible.devsec file
          ansible.builtin.file:
            path: "~/ansible.devsec"
            mode: '0600'
            state: touch
