---
# tasks file for weatherapp
-
  name: Debug Images
  ansible.builtin.debug:
    msg: "WeatherApp Version: {{ weatherapp_version }}"
-
  name: Creates directory
  ansible.builtin.file:
    path: /srv/weatherapp/nginx
    mode: '0660'
    state: directory
-
  name: Create network
  community.docker.docker_network:
    name: weatherapp
-
  name: Nginx Config
  ansible.builtin.copy:
    src: files/default.conf
    dest: /srv/weatherapp/nginx/default.conf
    mode: '0660'
    force: true
-
  name: Weatherapp frontend docker container
  community.docker.docker_container:
    name: weatherapp_frontend
    state: started
    image: ghcr.io/tomp736/weatherapp/weatherapp_frontend:{{ weatherapp_version }}
    restart_policy: always
    ports:
      - '8000'
    env:
      ENDPOINT="http://{{ hostvars[inventory_hostname]['ansible_host'] }}/api"
-
  name: Weatherapp backend docker container
  community.docker.docker_container:
    name: weatherapp_backend
    state: started
    image: ghcr.io/tomp736/weatherapp/weatherapp_backend:{{ weatherapp_version }}
    restart_policy: always
    ports:
      - '9000'
    env:
      APPID="{{ weatherapp_appid }}"
-
  name: WeatherApp nginx container
  community.docker.docker_container:
    name: weatherapp_nginx
    state: stopped
-
  name: WeatherApp nginx container
  community.docker.docker_container:
    name: weatherapp_nginx
    state: started
    image: nginx
    restart_policy: always
    ports:
      - '80:80'
    volumes:
      - /srv/weatherapp/nginx:/etc/nginx/conf.d

-
  name: Add to weatherapp network
  community.docker.docker_network:
    name: weatherapp
    connected:
      - weatherapp_frontend
      - weatherapp_backend
      - weatherapp_nginx
