---
# tasks file for weatherapp

- 
  name: Weatherapp frontend docker container
  community.docker.docker_container:
    name: weatherapp_frontend
    state: started
    image: ghcr.io/tomp736/weatherapp/weatherapp_frontend:0.1.0
    restart_policy: always
    ports:
      - '8000:8000'
- 
  name: Weatherapp backend docker container
  community.docker.docker_container:
    name: weatherapp_backend
    state: started
    image: ghcr.io/tomp736/weatherapp/weatherapp_backend:0.1.0
    restart_policy: always
    ports:
      - '9000:9000'
    env:
      APPID="{{ weatherapp_appid }}"