---
# tasks file for weatherapp

-
  name: Weatherapp frontend docker container
  community.docker.docker_container:
    name: weatherapp_frontend
    state: started
    image: ghcr.io/tomp736/weatherapp/weatherapp_frontend:{{ weatherapp_version }}
    restart_policy: always
    ports:
      - '8000:8000'
    env:
      ENDPOINT="http://{{ hostvars[inventory_hostname]['ansible_host'] }}:9000/api"
-
  name: Weatherapp backend docker container
  community.docker.docker_container:
    name: weatherapp_backend
    state: started
    image: ghcr.io/tomp736/weatherapp/weatherapp_backend:{{ weatherapp_version }}
    restart_policy: always
    ports:
      - '9000:9000'
    env:
      APPID="{{ weatherapp_appid }}"
