name: 'cron nightly deploy test'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
      
jobs:
  terraform:
    uses: ./.github/workflows/on_wfc_terraform.yml
    with:
      prefix: weatherapp-nightly
      environment: weatherapp_nightly
      tfapply: true
      tfdestroy: true
    secrets: inherit

  ansible:
    needs:
      - terraform
    uses: ./.github/workflows/on_wfc_ansible.yml
    with:
      environment: weatherapp_nightly
      site: true
      weatherapp: true
    secrets: inherit