name: 'cron deploy nightly'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
      
jobs:
  terraform-apply:
    uses: ./.github/workflows/on_wfc_deploy.yml
    with:
      prefix: weatherapp-nightly
      environment: weatherapp_nightly
      terraform_apply: true
      ansible_site: true
      ansible_weatherapp: true
      terraform_destroy: true
    secrets: inherit