name: 'cron nightly deploy test'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
      
jobs:
  deploy:
    uses: ./.github/workflows/on_wfc_terraform.yml
    with:
      prefix: weatherapp-nightly
      environment: weatherapp_nightly
      tfapply: true
      tfdestroy: true
    secrets: inherit