name: on pr open

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - dev
      - main

jobs:

  # run tffmt
  tffmt:      
    uses: ./.github/workflows/on_wfc_terraform_fmt.yml
    with:
      autofix_pr_branch: ${{ github.ref }}
    secrets: inherit