name: on pr open

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - dev
      - main

jobs:

  # run eslint scripts
  eslint:      
    uses: ./.github/workflows/on_wfc_npm_lint.yml
    secrets: inherit

  # run audit scripts
  audit:      
    uses: ./.github/workflows/on_wfc_npm_audit.yml
    secrets: inherit

  # run the docker_build workflow
  docker_build:
    needs:
      - eslint

    permissions:
      contents: read
      packages: write
      
    uses: ./.github/workflows/on_wfc_docker_build.yml
    with:
      image_tag: ${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.number }}
    secrets: inherit