name: 'on wfc ansible'

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment
        required: true
      site:
        type: boolean
        description: 'run site playbook'
        required: false
        default: false
      weatherapp:
        type: boolean
        description: 'run weatherapp playbook'
        required: false
        default: false

permissions:
  contents: read

jobs:
  ansible:
    name: 'ansible'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    concurrency: 
      group: ${{ inputs.environment }}
      cancel-in-progress: false
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - 
        name: Install dependencies Including Ansible
        working-directory: ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - 
        name: Download ansible_hosts_site
        uses: actions/download-artifact@v3
        with:
          name: ansible_hosts_site
          path: ansible/inventory
      -       
        name: ansible requirements
        working-directory: ansible
        run: |
          eval `ssh-agent`
          echo "${KEYFILE}" | ssh-add -
          ansible-galaxy install -r requirements.yml
        env:
          KEYFILE: ${{ secrets.DEPLOY_PRIVKEY }}
      -       
        name: site playbook
        working-directory: ansible
        run: |
          eval `ssh-agent`
          echo "${KEYFILE}" | ssh-add -
          ansible-playbook -i inventory/ansible_hosts_site site.yml
        env:
          KEYFILE: ${{ secrets.DEPLOY_PRIVKEY }}
      - 
        name: weatherapp playbook
        working-directory: ansible
        run: |
          eval `ssh-agent`
          echo "${KEYFILE}" | ssh-add -
          ansible-playbook -i inventory/ansible_hosts_site weatherapp.yml --extra-vars "weatherapp_appid=${{ secrets.WEATHERAPP_APPID }}"
        env:
          KEYFILE: ${{ secrets.DEPLOY_PRIVKEY }}