name: 'on wfc create pr'

on:
  workflow_call:
    inputs:
      source_branch:
        type: string
        description: 'source branch name'
        required: true
      target_branch:
        type: string
        description: 'target branch name'
        required: true
      promotion_tag:
        type: string
        description: 'promotion tag'
        required: true

jobs:
  create_pr:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target_branch }}

      - name: Reset promotion branch
        run: |
          git fetch origin ${{ inputs.source_branch }}:${{ inputs.source_branch }}
          git reset --hard ${{ inputs.source_branch }}

      - name: Create PR
        id: create_pull_request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          branch: ${{ inputs.target_branch }}-${{ inputs.promotion_tag }}