name: 'Dispatch Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'environment'
        required: false
        default: main
        options:
        - main
        - main-promotion
        - dev
        - dev-promotion
        - nightly
      terraform_apply:
        type: boolean
        description: 'terraform apply'
        required: false
        default: true
      ansible_site:
        type: boolean
        description: 'run site playbook'
        required: false
        default: true
      ansible_weatherapp:
        type: boolean
        description: 'run weatherapp playbook'
        required: false
        default: true
      ansible_weatherapp_version:
        type: string
        description: 'run weatherapp playbook'
        required: false
        default: '0.1.0'
      terraform_destroy:
        type: boolean
        description: 'terraform destroy'
        required: false
        default: false
      
jobs:
  deploy:
    uses: ./.github/workflows/on_wfc_deploy.yml
    with:
      environment: weatherapp_${{ inputs.environment }}
      resource_prefix: weatherapp-${{ inputs.environment }}
      terraform_apply: ${{ inputs.terraform_apply }}
      ansible_site: ${{ inputs.ansible_site }}
      ansible_weatherapp: ${{ inputs.ansible_weatherapp }}
      ansible_weatherapp_version: ${{ inputs.ansible_weatherapp_version }}
      terraform_destroy: ${{ inputs.terraform_destroy }}
    secrets: inherit