name: 'Dispatch Terraform Apply'

on:
  workflow_dispatch:
      
jobs:
  deploy:
    uses: ./.github/workflows/on_wfc_terraform.yml
    with:
      environment: weatherapp_${{ github.ref_name }}
      tfapply: true
    secrets: inherit