name: 'on wfc ansible'

on:
  workflow_call:

permissions:
  contents: read

jobs:
  ansible:
    name: 'ansible'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    concurrency: 
      group: ${{ inputs.environment }}
      cancel-in-progress: false
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3